// Code generated by gen_string_constants.go. DO NOT EDIT.
// Language: go
package constants

func (t MessageNotLogin) String() string {
	switch t {

	case LOGIN0:
		return "LOGIN0"
	case REGISTER0:
		return "REGISTER0"
	case SEND_SMS:
		return "SEND_SMS"
	case CLEAR_RMS:
		return "CLEAR_RMS"
	case CLIENT_INFO:
		return "CLIENT_INFO"
	case LOGIN:
		return "LOGIN"
	case FORGET_PASS:
		return "FORGET_PASS"
	case FORGET_PASS_IMEI:
		return "FORGET_PASS_IMEI"
	case REGISTER:
		return "REGISTER"
	case REGISTER_IMEI:
		return "REGISTER_IMEI"
	case DOI_MAT_KHAU:
		return "DOI_MAT_KHAU"
	}
	return ""
}
