// Code generated by gen_string_constants.go. DO NOT EDIT.
// Language: go
package constants

func (t ItemType) String() string {
	switch t {

	case TYPE_NGOC:
		return "TYPE_NGOC"
	case TYPE_NON:
		return "TYPE_NON"
	case TYPE_VU_KHI:
		return "TYPE_VU_KHI"
	case TYPE_AO:
		return "TYPE_AO"
	case TYPE_DAY_CHUYEN:
		return "TYPE_DAY_CHUYEN"
	case TYPE_GANG:
		return "TYPE_GANG"
	case TYPE_NHAN:
		return "TYPE_NHAN"
	case TYPE_QUAN:
		return "TYPE_QUAN"
	case TYPE_BOI:
		return "TYPE_BOI"
	case TYPE_GIAY:
		return "TYPE_GIAY"
	case TYPE_BUA:
		return "TYPE_BUA"
	case TYPE_THU_NUOI:
		return "TYPE_THU_NUOI"
	case TYPE_MAT_NA:
		return "TYPE_MAT_NA"
	case TYPE_YOROI:
		return "TYPE_YOROI"
	case TYPE_GIA_TOC:
		return "TYPE_GIA_TOC"
	case TYPE_MAT:
		return "TYPE_MAT"
	case TYPE_BI_KIP:
		return "TYPE_BI_KIP"
	}
	return ""
}
