package constants

type EffectType int

const (
	EFF_COM_NAM = iota
	EFF_TEMPURA
	EFF_KATSUDON
	EFF_Sashimi
	EFF_GA_QUAY
	EFF_FIRED_HURT
	EFF_ICED
	EFF_DIZZY
	EFF_5_BUFF_HP
	EFF_FIRE_INVISIBLE
	EFF_MANA_SHIELD
	EFF_MISS_ALL
	EFF_EXP
	EFF_INCREASE_HP_FROM_TEAM
	EFF_DIE // PHI CHIEN DAU
	EFF_INVISIBLE1
	EFF_INVISIBLE2
	EFF_DECREASE_HP_INCREASE_ATTACK
	EFF_LOCKED
	EFF_RESIST
	EFF_DECREASE_TIME
	EFF_INCREASE_HP
	EFF_X2_EXP
	EFF_BI_DUOC
	EFF_INCREASE_EXACT
	EFF_INCREASE_POWER
	EFF_INCREASE_RESIST
	EFF_INCEASE_HP
	EFF_FOOD_5X
	EFF_SINH_MENH_DAN
	EFF_FOOD_6X
	EFF_FOOD_7X
	EFF_X3_EXP
	EFF_X4_EXP
	EFF_THI_LUYEN
	EFF_FOOD_9X
	EFF_LDCC
	EFF_LD_NGOI_SAO
	EFF_LD_TRON
	EFF_LD_ONG_TRANG
	EFF_THIEN_NHAN_PHU
	EFF_KHAI_NHAN_PHU
	EFF_PET_BI_RE_HANH
)
