package constants

//go:generate go run ../generate/gen_string_constants.go -pkg=constants -type=ItemType
type ItemType int

const (
	TYPE_NGOC             = 34
	TYPE_NON              = 0
	TYPE_VU_KHI           = 1
	TYPE_AO               = 2
	TYPE_DAY_CHUYEN       = 3
	TYPE_GANG             = 4
	TYPE_NHAN             = 5
	TYPE_QUAN             = 6
	TYPE_BOI              = 7
	TYPE_GIAY             = 8
	TYPE_BUA              = 9
	TYPE_THU_NUOI         = 10
	TYPE_MAT_NA           = 11
	TYPE_YOROI            = 12
	TYPE_GIA_TOC          = 13
	TYPE_MAT              = 14
	TYPE_BI_KIP           = 15
	TYPE_TASK1            = 23
	TYPE_TASK2            = 24
	TYPE_TASK3            = 25
	CAN_CAU_CA            = 597
	THIEN_BIEN_LENH       = 572
	MAX_THAN_THU_EXPS     = 10_000
	HAI_MA_1_ID           = 584
	HAI_MA_2_ID           = 585
	HAI_MA_3_ID           = 586
	DI_LONG_1_ID          = 587
	HOA_LONG_ID           = 583
	DI_LONG_2_ID          = 588
	DI_LONG_3_ID          = 589
	ST_QUAI_ID            = 102
	ST_NGUOI_ID           = 103
	TYPE_DI_LONG          = 0
	TYPE_HAI_MA           = 1
	TYPE_HOA_LONG         = 2
	HUYEN_TINH_NGOC       = 652
	HUYET_NGOC            = 653
	VU_KHI_OPTION_ID      = 106
	OPTION_TAN_CONG_ID    = 73
	OPTION_CHI_MANG_ID    = 114
	OPTION_GIAM_TRU_ST_ID = 124
	TRANG_BI_OPTION_ID    = 107
	TRANG_SUC_OPTION_ID   = 108
	EXP_ID                = 104
	GIA_KHAM_OPTION_ID    = 123
	LAM_TINH_NGOC         = 654
	LUC_NGOC              = 655
	MAX_ST_NGUOI          = 200
	HP_TOI_DA             = 50
	MP_TOI_DA             = 50
	MAX_CHI_MANG          = 5
	KHANG_ST_CHI_MANG     = 5
	MOI_GIAY_HOI_PHUC_HP  = 5
	MOI_GIAY_HOI_PHUC_MP  = 5
	MAX_TAN_CONG          = 200
	MAX_GIAM_TRU_ST       = 10
	PHAN_DON              = 5
	ST_CHI_MANG           = 500
	CHINH_XAC             = 35
	NE_DON                = 35
	KHANG_TAT_CA          = 10
	Geningan              = 685
	Chuuningan            = 686
	Jougan                = 687
	Seningan              = 688
	Kyubigan              = 689
	Rinnegan              = 690
	Sharingan             = 691
	Tenseigan             = 692
	Ketsuryugan           = 693
	Sukaigan              = 694
)
