// Code generated by gen_string_constants.go. DO NOT EDIT.
// Language: go
package constants

func (t HookType) String() string {
	switch t {

	case HOOK_NET_WORK_START:
		return "HOOK_NET_WORK_START"
	case HOOK_NEW_CONNECTION_ENTER:
		return "HOOK_NEW_CONNECTION_ENTER"
	case HOOK_NET_WORK_STOP:
		return "HOOK_NET_WORK_STOP"
	case HOOK_APP_START:
		return "HOOK_APP_START"
	case HOOK_APP_TERMINATE:
		return "HOOK_APP_TERMINATE"
	case HOOK_APP_END:
		return "HOOK_APP_END"
	}
	return ""
}
