package config

type AppConfig struct {
	DbName               string `json:"db_name"`
	Username             string `json:"db_user"`
	Password             string `json:"db_password"`
	Host                 string `json:"db_host"`
	Port                 string `json:"db_port"`
	Migrate              bool   `json:"migrate"`
	InitDataTest         bool   `json:"init_data_test"`
	ServerPort           string `json:"server_port"`
	DropDb               bool   `json:"drop_db"`
	PathImages           string `json:"path_images"`
	PathCharPart         string `json:"path_char_part"`
	PathMessages         string `json:"path_messages"`
	Debug                bool   `json:"debug"`
	LogFile              string `json:"log_file"`
	ResPath              string `json:"res_path"`
	UseSQL               bool   `json:"use_sql"`
	MongoDBURL           string `json:"mongodb_url"`
	NHooksWorkers        int    `json:"n_hooks_workers"`
	HooksTimeOut         int64  `json:"hooks_timeout"`
	HookQueueSize        int    `json:"hook_queue_size"`
	LogSql               bool   `json:"log_sql"`
	VsData               byte   `json:"vs_data"`
	VsItem               byte   `json:"vs_item"`
	VsMap                byte   `json:"vs_map"`
	VsSkill              byte   `json:"vs_skill"`
	UpdateMapDelayMillis int64  `json:"update_map_delay"`
}

type GameConfig struct {
	DropItemPercent     int    `json:"drop-item-percent"`
	PercentTaTl         int    `json:"percent-ta-tl"`
	TimeRefreshMob      int64  `json:"time-refresh-mob"`
	MinDaLv             int    `json:"min-da-lv"`
	NYen                int    `json:"n-yen"`
	NDa                 int    `json:"n-da"`
	LangCoItemIds       []int  `json:"lang-co-item-ids"`
	MapMoiItemIds       []int  `json:"map-moi-item-ids"`
	VdmqItemIds         []int  `json:"vdmq-item-ids"`
	BossItemLv45        []int  `json:"boss-item-lv45"`
	BossItemLv55        string `json:"boss-item-lv55"`
	BossItemLv60        string `json:"boss-item-lv60"`
	BossItemLv65        string `json:"boss-item-lv65"`
	BossItemLv75        string `json:"boss-item-lv75"`
	BossItemLv99        string `json:"boss-item-lv99"`
	BossItemLv90        string `json:"boss-item-lv90"`
	BossItemLv100       string `json:"boss-item-lv100"`
	BossItemLv110       string `json:"boss-item-lv110"`
	BossDefaultItem     string `json:"boss-default-item"`
	BossVuiXuan         string `json:"boss-vui-xuan"`
	BossTuanThu         string `json:"boss-tuan-thu"`
	BossItemLc          string `json:"boss-item-lc"`
	BossItemMapmoi      string `json:"boss-item-mapmoi"`
	BossItemSukien      string `json:"boss-item-sukien"`
	MinYenBoss          string `json:"min-yen-boss"`
	MaxYenBoss          string `json:"max-yen-boss"`
	MaxBoss             string `json:"max-boss"`
	NItemsBoss          string `json:"n-items-boss"`
	ThuongLv70          string `json:"thuong-lv70"`
	ThuongLv90          string `json:"thuong-lv90"`
	ThuongLv130         string `json:"thuong-lv130"`
	MultiExp            string `json:"multi-exp"`
	TimeBaoTri          string `json:"time-bao-tri"`
	NThreadStop         string `json:"n-thread-stop"`
	MaxClient           string `json:"max-Client"`
	TimeDisconnect      string `json:"time-Disconnect"`
	TimeDestroyMap      string `json:"time-Destroy-Map"`
	TimeRemoveResource  string `json:"time-remove-resource"`
	DifferUseItemTime   string `json:"differ-use-item-time"`
	MaxUseItemFast      string `json:"max-use-item-fast"`
	PercentDameBoss     string `json:"percent-dame-boss"`
	BossWaitTimeUnit    string `json:"boss-wait-time-unit"`
	MomentBossRefresh   string `json:"moment-boss-refresh"`
	MomentRefreshBattle string `json:"moment-refresh-battle"`
	WaitingTime         string `json:"waiting-time"`
	StartTime           string `json:"start-time"`
	DamagePeopleRate    string `json:"damage-people-rate"`
	Debug               string `json:"debug"`
	MinTimeResetPoint   string `json:"min-time-reset-point"`
	MaxThreadCount      string `json:"max-thread-count"`
	TimeRunShinwaThread string `json:"time-run-shinwa-thread"`
	LatHinhID           string `json:"lat-hinh-id"`
	YenLatHinh          string `json:"yen-lat-hinh"`
	YenTa               string `json:"yen-ta"`
	YenTl               string `json:"yen-tl"`
	YenRuongMayMan      string `json:"yen-ruong-may-man"`
	YenRuongTinhSao     string `json:"yen-ruong-tinh-sao"`
	YenRuongMaQuai      string `json:"yen-ruong-ma-quai"`
	LdgtRewardItemID    string `json:"ldgt-reward-item-id"`
	EventType           string `json:"event-type"`
	EventInput0         string `json:"event-input0"`
	EventInput2         string `json:"event-input2"`
	EventInput3         string `json:"event-input3"`
	RewardThienBang     string `json:"reward-thien-bang"`
	RewardDiaBang       string `json:"reward-dia-bang"`
}
